
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springFile?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: flamme1004!

  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

  error:
    whitelabel:
      enabled: false

logging:
  level:
    org:
      springframework:
      hibernate:
        type:
        descriptor:
        sql: trace
